Corrected validations to run properly for color, weight, and material. Updated unit test, got an error: Ran 1 test in 0.005s
FAILED (errors=1)

Error
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: knittedGutsTest
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\PycharmProjects\knittedSkeleton\myapp\knittedGutsTest.py", line 6, in <module>
    from app import YarnCollection
  File "C:\Users\smith\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\app\__init__.py", line 4, in <module>
    app.config.from_object("config")
  File "C:\Users\smith\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\config.py", line 229, in from_object
    obj = import_string(obj)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\utils.py", line 611, in import_string
    raise ImportStringError(import_name, e).with_traceback(
  File "C:\Users\smith\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\utils.py", line 595, in import_string
    __import__(import_name)
werkzeug.utils.ImportStringError: import_string() failed for 'config'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' not found.

Original exception:

ModuleNotFoundError: No module named 'config'.
NEED TO CORRECT